name: QA (automatic)

on:
  pull_request:
    branches:
      - main
      - staging
      - develop
      - release
      - 'dev-*'
      - 'bugfix-*'
      - 'hotfix-*'
      - 'feat-*'
      - 'feature-*'
      - 'story-*'

    paths:
      - '**/*'

    # see <https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#discussion>
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - unlocked

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.13"

jobs:
  qa:
    name: QA
    runs-on: "ubuntu-latest"
    environment: "local"
    env: {}

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Action - install justfile tool
        uses: extractions/setup-just@v3
        with:
          just-version: "1.25.2"

      - name: Action - install Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Action - install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.12.0

      - name: Setup - ping basic tools and perform pre-installation
        shell: bash
        run: |-
          just --version
          python3 --version
          python3 -m pip install --upgrade pip wheel
          just setup

      - name: STEP 1 - build code
        shell: bash
        run: |-
          just build

      - name:  STEP 2 - check linting
        shell: bash
        run: |-
          just prettify

      - name:  STEP 3 - run unit tests
        shell: bash
        run: |-
          just tests-unit
